### PR TITLE
Replace python with collect-metrics lambda function

### PR DESCRIPTION
**Pull request by lox**
This replaces the existing python + docker implementation with a Lambda function and a cloudwatch events stream to execute the lambda function every few minutes.

### CODE REVIEW

**Comment by lox** [comment]
I'll run this for a while and fix any bugs, but it's feature complete now.

**Comment by lox** [comment]
The permissions granted in the IAM role are pretty broad: 

```
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: [ lambda.amazonaws.com ]
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Path: "/"
      Policies:
        - PolicyName: root
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - cloudformation:DescribeStacks
                  - events:PutRule
                  - events:PutTargets
                  - lambda:*
                  - cloudwatch:PutMetricData
                Resource: "*"
```

Good chance this could be distilled down.

**Comment by lox** [comment]
Happy for you to merge this @toolmantim

**Comment by toolmantim** [comment]
Done! Can we make this part of the standard Buildkite AWS stack?

**Comment by lox** [comment]
Yeah, I'm trying to think of the best way to do this.

**Pull request merged**
